import UIKit

enum SFSym : String
{
    case _15_square_fill
    case display
    case _27_circle_fill
    case tag_fill
    case macwindow_badge_plus
    case airplane_circle
    case _18_square
    case kipsign_square
    case _3_circle_fill
    case tropicalstorm
    case arrow_up_right_app_fill
    case centsign_square
    case minus_plus_batteryblock
    case info_circle
    case speaker_2_fill
    case xmark_seal_fill
    case rectangle_split_2x2_fill
    case lirasign_circle_fill
    case goforward_90
    case bookmark_circle
    case _46_circle
    case tray_2
    case _4_circle
    case cloud_moon_fill
    case h_circle_fill
    case arrowtriangle_up_fill
    case plus_message_fill
    case hare_fill
    case j_circle
    case k_square_fill
    case cursorarrow_motionlines_click
    case hand_point_left_fill
    case xmark_rectangle_portrait
    case stopwatch_fill
    case _15_circle
    case speaker_zzz_fill
    case dial
    case globe
    case arrowshape_turn_up_left
    case arrow_2_circlepath_circle
    case magnifyingglass_circle
    case tablecells_fill
    case francsign_square
    case doc_fill_badge_ellipsis
    case _41_square_fill
    case envelope
    case questionmark_video
    case app_badge
    case _20_square
    case doc_text_viewfinder
    case purchased
    case person_crop_square_fill_and_at_rectangle
    case doc_circle_fill
    case _22_circle_fill
    case xmark_shield
    case moon_circle
    case _07_circle
    case _43_square
    case person_crop_circle_fill_badge_minus
    case tray_full
    case square_on_square_dashed
    case plus_circle_fill
    case paperclip_circle
    case figure_wave_circle_fill
    case square_stack_3d_up_slash
    case phone_arrow_right
    case plus_rectangle_fill
    case arrowshape_zigzag_right_fill
    case person_crop_circle_badge_exclamationmark
    case tv_music_note
    case figure_walk
    case _26_square
    case text_justify
    case airplane
    case person_crop_circle_badge_exclam
    case plus_rectangle_fill_on_folder_fill
    case chevron_right_circle_fill
    case video_badge_plus_fill
    case mail
    case forward
    case equal_square_fill
    case bolt_horizontal_circle_fill
    case b_circle
    case restart_circle
    case umbrella
    case hearingaid_ear
    case light_min
    case cloud_sun_rain_fill
    case tag_circle_fill
    case hryvniasign_circle_fill
    case dpad_down_fill
    case paintpalette
    case t_bubble_fill_ar
    case moon_circle_fill
    case arrow_left_to_line
    case square_fill
    case square_split_diagonal_fill
    case chevron_compact_up
    case rectangle_stack_badge_minus
    case printer_fill
    case alarm_fill
    case goforward_90_ar
    case bell_badge
    case tag_slash
    case stethoscope
    case cloud_fog_fill
    case smoke_fill
    case pesosign_circle_fill
    case printer_dotmatrix
    case _4_alt_circle
    case questionmark_diamond_fill_ar
    case _17_square
    case calendar_badge_plus
    case dial_min
    case envelope_badge
    case tugriksign_square_fill
    case _06_square
    case rectangle_righthalf_inset_fill
    case trash_circle_fill
    case dpad_left_fill
    case icloud
    case exclamationmark_icloud_fill
    case rectangle_fill_on_rectangle_angled_fill
    case text_bubble_rtl
    case lock_shield_fill
    case square_grid_3x3_fill
    case centsign_circle
    case square_fill_on_square_fill
    case speaker_zzz
    case bahtsign_circle
    case _4_square
    case plus_square_on_square
    case _33_square
    case lock_rotation_open
    case _11_square
    case airport_extreme_tower
    case bolt_car
    case d_circle_fill
    case _12_square_fill
    case link_badge_plus
    case arrowtriangle_down
    case _05_circle
    case florinsign_square
    case flag_circle
    case hand_raised
    case rectangle_arrowtriangle_2_inward
    case sparkles
    case cloud_snow_fill
    case square_and_arrow_up_on_square_fill
    case _36_circle
    case square_stack
    case arrow_up_doc_on_clipboard
    case _2_circle_fill
    case doc_badge_ellipsis
    case textformat
    case g_square_fill
    case phone_arrow_down_left
    case skew
    case scanner_fill
    case speaker_wave_1
    case _44_circle
    case rectangle_and_arrow_up_right_and_arrow_down_left_slash
    case lt_rectangle_roundedtop_fill
    case exclamationmark_shield
    case n_circle_fill
    case ipodtouch
    case speaker_wave_3
    case zl_rectangle_roundedtop_fill
    case xmark_bin_fill
    case c_square_fill
    case zl_rectangle_roundedtop
    case circle_bottomthird_split
    case lirasign_square_fill
    case arrow_counterclockwise
    case number_circle
    case gobackward_90_hi
    case arrowtriangle_down_circle
    case gobackward_10
    case d_square
    case arrow_up_bin
    case person_crop_circle_badge_questionmark
    case minus_magnifyingglass
    case suit_club_fill
    case giftcard
    case arrow_left_square_fill
    case o_circle_fill
    case gearshape_2_fill
    case cloud_fog
    case table_badge_more
    case a
    case hand_point_down
    case figure_walk_diamond
    case arrow_clockwise
    case _19_square
    case greaterthan_square
    case scroll
    case rhombus
    case speedometer
    case heart_text_square_fill
    case circle_grid_hex_fill
    case francsign_square_fill
    case bitcoinsign_circle_fill
    case wave_3_left_circle_fill
    case bubble_middle_bottom
    case tray_and_arrow_down_fill
    case pause_circle
    case pip_swap
    case ant_circle_fill
    case applewatch
    case square_and_at_rectangle
    case binoculars_fill
    case pip_fill
    case arrowtriangle_up_square
    case bolt_horizontal_icloud
    case hand_point_up_fill
    case chevron_left_slash_chevron_right
    case square_fill_on_circle_fill
    case decrease_quotelevel
    case rectangle_and_pencil_and_ellipsis
    case arrow_up_left
    case c_circle_fill
    case lb_rectangle_roundedbottom
    case text_and_command_macwindow
    case zr_rectangle_roundedtop_fill
    case f_square
    case goforward_10
    case bolt_heart
    case externaldrive_badge_wifi
    case shield
    case cloud_moon_bolt_fill
    case stop_fill
    case doc_append
    case cruzeirosign_circle_fill
    case house_circle
    case faxmachine
    case _10_square_fill
    case bubble_right
    case chart_pie_fill
    case arrow_up_message
    case dock_arrow_down_rectangle
    case gift
    case recordingtape
    case dongsign_square
    case z_square
    case arrow_up_right_and_arrow_down_left_rectangle_fill
    case textformat_alt
    case photo_on_rectangle
    case square_split_1x2
    case _16_square_fill
    case text_justifyright
    case bubble_middle_top_fill
    case cedisign_circle
    case wave_3_right
    case questionmark_folder
    case manatsign_square
    case wrench_fill
    case square_fill_text_grid_1x2
    case exclamationmark_octagon
    case sportscourt_fill
    case play_slash_fill
    case arrow_down_left_video_rtl
    case camera_metering_center_weighted
    case person_2_square_stack_fill
    case _00_circle_fill
    case _4_alt_square_fill
    case arrowshape_turn_up_right_fill
    case cloud_fill
    case arrowtriangle_left_square
    case bell_badge_fill
    case _24_square_fill
    case plus_diamond_fill
    case arrowtriangle_right_and_line_vertical_and_arrowtriangle_left
    case _10_circle
    case guaranisign_square_fill
    case _03_circle_fill
    case _20_circle_fill
    case aspectratio
    case textformat_subscript
    case dot_square_fill
    case fx
    case arrowshape_turn_up_left_2_fill
    case rb_rectangle_roundedbottom
    case gift_fill
    case cpu
    case puzzlepiece_fill
    case minus_square
    case pesosign_square_fill
    case wallet_pass_fill
    case app_gift
    case greetingcard
    case wonsign_square_fill
    case text_bubble
    case questionmark_square_dashed
    case rectangle_split_2x1_fill
    case _29_circle
    case rectangle_inset_bottomleft_fill
    case square_grid_3x3_middleleft_fill
    case millsign_circle_fill
    case rectangle_fill_badge_plus
    case cruzeirosign_square_fill
    case square_3_stack_3d
    case arrow_uturn_right_circle
    case phone_badge_plus
    case rectangle_leftthird_inset_fill
    case bookmark_slash
    case arrow_up_and_down
    case dongsign_circle_fill
    case scale_3d
    case rosette
    case text_badge_star
    case square_2_stack_3d_top_fill
    case square_and_arrow_down_on_square
    case a_circle
    case internaldrive_fill
    case square_grid_3x3_middle_fill
    case person_crop_circle_badge_questionmark_ar
    case hand_thumbsup
    case francsign_circle_fill
    case pesetasign_circle_fill
    case icloud_slash_fill
    case circle_circle_fill
    case p_square
    case arrow_up_square
    case rectangle_split_3x1
    case _26_circle
    case textformat_abc_dottedunderline
    case pano_fill
    case arrow_triangle_2_circlepath_circle_fill
    case person_icloud
    case keyboard_onehanded_right
    case pin_circle_fill
    case _49_circle_fill
    case moon_stars_fill
    case xmark_square_fill
    case xmark_seal
    case arrowshape_turn_up_right
    case _21_circle_fill
    case printer
    case location_fill
    case at_badge_plus
    case video_slash
    case r_rectangle_roundedbottom
    case arrow_left_and_right_righttriangle_left_righttriangle_right_fill
    case z_circle
    case sun_haze
    case arrow_left_circle
    case shift
    case xmark_bin_circle_fill
    case square_on_square_squareshape_controlhandles
    case rublesign_circle
    case shuffle
    case comb_fill
    case arrowtriangle_left_fill
    case text_aligncenter
    case doc_on_clipboard_fill
    case wake
    case q_square
    case amplifier
    case waveform
    case speaker_wave_2_circle
    case house_circle_fill
    case rublesign_circle_fill
    case _38_square_fill
    case rectangle_expand_vertical
    case l_circle_fill
    case person_crop_circle
    case star_lefthalf_fill
    case keyboard_chevron_compact_left
    case person_3
    case folder_fill_badge_gear
    case lock_rectangle
    case building_2_crop_circle
    case circles_hexagonpath_fill
    case rectangle_and_text_magnifyingglass
    case lock_square
    case arrow_up_right_video_fill_rtl
    case music_house
    case smiley_fill
    case sheqelsign_square
    case sheqelsign_circle
    case plus_app_fill
    case arrow_up_right_diamond
    case slider_vertical_3
    case plus_square_fill_on_square_fill
    case d_circle
    case arrowshape_turn_up_left_circle_fill
    case squares_below_rectangle
    case chevron_right
    case lock_square_stack_fill
    case lirasign_square
    case ipad
    case _22_circle
    case minus_rectangle_portrait
    case arrow_left_and_right_square
    case arrow_right_to_line_alt
    case _45_circle_fill
    case square_grid_3x3_middleright_fill
    case arrowtriangle_left_circle_fill
    case airpodspro
    case square_and_arrow_up_fill
    case info_circle_fill
    case lightbulb_slash
    case backward_frame_fill
    case v_square
    case sparkle
    case arrow_up_and_person_rectangle_turn_left
    case arrow_left_and_right_circle
    case arrow_triangle_2_circlepath_camera
    case t_bubble_ar
    case _33_square_fill
    case tugriksign_circle
    case doc_circle
    case _22_square_fill
    case dpad
    case camera_on_rectangle
    case e_circle
    case play_slash
    case suit_heart
    case arrow_branch
    case rectangle_grid_2x2
    case eurosign_circle
    case arrow_up_right_square_fill
    case folder_fill_badge_person_crop
    case cube_box
    case chevron_up_chevron_down
    case flowchart_fill
    case line_horizontal_3_circle_fill
    case square_grid_3x2_fill
    case bahtsign_square
    case suit_diamond_fill
    case plus_message
    case _20_circle
    case xmark_rectangle
    case largecircle_fill_circle
    case dollarsign_square_fill
    case bus_doubledecker_fill
    case minus_plus_batteryblock_fill
    case speaker_wave_2
    case number_square_fill
    case l_joystick_down
    case star_circle
    case ipodshuffle_gen2
    case arrow_turn_down_right
    case suit_spade
    case burn
    case ellipsis
    case arrowshape_zigzag_right
    case _16_circle
    case j_square_fill
    case move_3d
    case exclamationmark
    case speaker_slash_circle_fill_rtl
    case minus_rectangle
    case heart_slash
    case applescript
    case plus
    case list_bullet_rectangle
    case chevron_right_circle
    case pip
    case arrow_right_to_line
    case arrow_up_and_down_and_arrow_left_and_right
    case rectangle_fill_badge_checkmark
    case menubar_rectangle
    case leaf_arrow_circlepath
    case gobackward_45
    case bin_xmark_fill
    case paintbrush_fill
    case arrow_down_right
    case _31_square
    case _34_circle_fill
    case x_squareroot
    case nose
    case increase_indent
    case tv
    case triangle_lefthalf_fill
    case backward_frame
    case yensign_circle
    case bolt_slash
    case _35_circle
    case square_stack_3d_down_right_fill
    case laptopcomputer
    case _25_circle
    case r1_rectangle_roundedbottom
    case pip_enter
    case macpro_gen3
    case speaker_slash_fill_rtl
    case bubble_middle_bottom_fill
    case hammer_fill
    case questionmark_diamond_ar
    case hourglass_tophalf_fill
    case rectangle_roundedtop_fill
    case chevron_up_circle
    case doc_richtext
    case square_split_1x2_fill
    case _06_circle
    case person_crop_circle_fill_badge_plus
    case arrow_up_left_and_arrow_down_right_circle
    case applewatch_slash
    case rectangle_slash_fill
    case _01_circle
    case bell
    case building_columns_fill
    case die_face_2_fill
    case _32_circle
    case goforward_75_hi
    case delete_left_fill
    case circle_fill_square_fill
    case checkmark_shield
    case phone_fill_arrow_down_left
    case _6_square_fill
    case arrow_clockwise_circle_fill
    case checkmark_rectangle
    case nairasign_square_fill
    case cart
    case pills
    case goforward_30_ar
    case homekit
    case arrow_2_squarepath
    case xmark_bin_circle
    case eyeglasses
    case square_circle_fill
    case externaldrive_fill_badge_timemachine
    case die_face_2
    case hifispeaker_fill
    case arrow_up_left_and_down_right_and_arrow_up_right_and_down_left
    case wallet_pass
    case lifepreserver
    case r2_rectangle_roundedtop
    case person_circle_fill
    case l_square_fill
    case goforward_plus
    case message_circle
    case arrowtriangle_up_square_fill
    case building_2
    case flame
    case selection_pin_in_out
    case arrow_up_arrow_down_circle
    case goforward_45
    case list_and_film
    case person_badge_minus
    case location_fill_viewfinder
    case line_horizontal_3_decrease
    case fiberchannel
    case arrow_up
    case arrow_up_and_down_circle
    case film_fill
    case lock_circle
    case rublesign_square_fill
    case barometer
    case play_rectangle
    case florinsign_square_fill
    case bubble_middle_top
    case externaldrive_badge_timemachine
    case flag
    case square_stack_3d_up_badge_a
    case icloud_and_arrow_up
    case purchased_circle_fill
    case line_diagonal
    case questionmark_circle_fill_ar
    case person_crop_circle_badge_checkmark
    case circle_grid_2x2_fill
    case y_square_fill
    case lb_rectangle_roundedbottom_fill
    case gearshape
    case triangle_fill
    case a_book_closed
    case v_circle
    case manatsign_circle_fill
    case goforward_10_hi
    case t_square_fill
    case person_fill_badge_minus
    case text_badge_plus
    case _42_circle
    case person_3_fill
    case gobackward_60_ar
    case xserve
    case text_cursor_ar
    case textformat_123_ar
    case questionmark_ar
    case person_icloud_fill
    case ellipsis_circle
    case function
    case dongsign_square_fill
    case pin_circle
    case rectangle_3_offgrid_bubble_left
    case rectangle_badge_xmark
    case speaker_1_fill
    case arrow_triangle_swap
    case sterlingsign_circle
    case rectangle_split_2x1
    case xmark_icloud
    case gobackward_75_ar
    case star_slash_fill
    case playpause
    case arrow_turn_down_left
    case banknote_fill
    case arrow_up_and_person_rectangle_turn_right
    case arrow_uturn_right_square
    case arrow_down_left_square_fill
    case candybarphone
    case person_crop_circle_fill_badge_exclam
    case multiply_circle
    case rectangle_3_offgrid_fill
    case _0_square_fill
    case hand_wave_fill
    case dot_squareshape
    case _0_square
    case checkmark_rectangle_portrait_fill
    case lock_doc_fill
    case leaf_arrow_triangle_circlepath
    case arrow_turn_right_down
    case goforward_10_ar
    case minus
    case r_square_fill_on_square_fill
    case alt
    case apps_iphone
    case thermometer
    case pesetasign_square_fill
    case xmark_circle_fill
    case folder_circle_fill
    case paragraph
    case cart_fill
    case scissors_badge_ellipsis
    case bubble_left_and_bubble_right_fill
    case tray
    case exclamationmark_shield_fill
    case abc
    case arrow_up_left_circle
    case arrow_down_square_fill
    case camera_rotate
    case circle_righthalf_fill
    case multiply_square_fill
    case checkerboard_rectangle
    case rectangle_split_3x1_fill
    case minus_circle_fill
    case perspective
    case plus_rectangle_on_rectangle
    case mic_slash
    case smallcircle_circle_fill
    case teletype_circle_fill
    case arrowtriangle_right_circle
    case rectangle_and_paperclip
    case cloud_sun
    case camera_fill
    case chart_pie
    case key
    case centsign_square_fill
    case camera_metering_none
    case lock
    case person_circle
    case phone_fill_badge_plus
    case hand_thumbsdown
    case wonsign_square
    case circle_grid_cross
    case icloud_circle_fill
    case flag_badge_ellipsis
    case a_magnify
    case bolt_fill
    case circle_grid_cross_down_fill
    case umbrella_fill
    case _04_circle
    case _18_circle
    case millsign_circle
    case bolt_fill_batteryblock_fill
    case square_dashed_inset_fill
    case person_fill_questionmark
    case capslock
    case arrow_left_square
    case mail_stack_fill
    case m_circle_fill
    case arrow_triangle_2_circlepath_camera_fill
    case rupeesign_circle
    case line_horizontal_3
    case smoke
    case square_stack_3d_up_badge_a_fill
    case camera_metering_partial
    case _1_circle_fill
    case radiowaves_right
    case folder_fill_badge_minus
    case squareshape_split_3x3
    case line_3_crossed_swirl_circle
    case keyboard_chevron_compact_down
    case sun_min_fill
    case tengesign_circle_fill
    case _38_circle_fill
    case ant_fill
    case _46_circle_fill
    case person_badge_plus
    case bookmark_circle_fill
    case graduationcap_fill
    case arrow_right_doc_on_clipboard
    case f_cursive_circle
    case exclamationmark_triangle_fill
    case curlybraces
    case line_horizontal_2_decrease_circle_fill
    case crown
    case arrow_down_right_square_fill
    case arrow_rectanglepath
    case bolt_badge_a_fill
    case pencil_and_ellipsis_rectangle
    case line_horizontal_2_decrease_circle
    case doc_richtext_fill_ar
    case camera_metering_center_weighted_average
    case camera_aperture
    case hand_point_right_fill
    case triangle_circle
    case exclamationmark_octagon_fill
    case hand_point_right
    case icloud_circle
    case grid
    case _16_circle_fill
    case envelope_badge_fill
    case location_circle_fill
    case stop
    case wonsign_circle
    case cursorarrow_square
    case lifepreserver_fill
    case u_square
    case ruler
    case questionmark_video_fill
    case square_grid_3x3_topleft_fill
    case arrow_down_left_video_fill
    case gobackward_75
    case speaker_1
    case square_stack_3d_up_fill
    case gamecontroller_fill
    case pencil_circle_fill
    case plus_circle
    case cloud_moon_rain_fill
    case bitcoinsign_square_fill
    case _32_square
    case rectangle_badge_plus
    case view_2d
    case drop_triangle_fill
    case checkmark_rectangle_portrait
    case exclamationmark_bubble
    case arrowshape_turn_up_left_fill
    case externaldrive_fill_badge_minus
    case hexagon
    case envelope_open
    case p_circle
    case _49_square
    case l_rectangle_roundedbottom
    case phone_arrow_up_right
    case arrow_right_circle
    case rectangle_slash
    case flag_slash_circle
    case equal
    case arrowtriangle_left_and_line_vertical_and_arrowtriangle_right
    case hryvniasign_square
    case zzz
    case lock_square_stack
    case play_circle_fill
    case m_square
    case book_closed
    case hourglass_bottomhalf_fill
    case suit_club
    case square_grid_3x3_topright_fill
    case pin_fill
    case minus_circle
    case hexagon_fill
    case _21_circle
    case banknote
    case sterlingsign_square
    case hammer
    case speaker_slash_circle_rtl
    case bag_badge_minus
    case slash_circle_fill
    case thermometer_snowflake
    case p_circle_fill
    case menubar_arrow_up_rectangle
    case _02_square
    case externaldrive_fill_badge_plus
    case h_square_fill
    case cloud_sleet
    case icloud_and_arrow_down
    case w_square_fill
    case arrowtriangle_left
    case minus_diamond_fill
    case questionmark_video_rtl
    case rectangle_inset_topright_fill
    case arrow_triangle_turn_up_right_circle
    case lock_fill
    case _0_circle_fill
    case _6_alt_square
    case heart_slash_circle_fill
    case mount_fill
    case arrowtriangle_right_square
    case clear_fill
    case shadow
    case hare
    case giftcard_fill
    case _27_circle
    case circle_square
    case exclamationmark_bubble_fill
    case j_square_fill_on_square_fill
    case externaldrive_fill
    case guitars_fill
    case apps_iphone_landscape
    case pianokeys
    case infinity
    case folder_fill
    case quote_bubble
    case arrow_down_app_fill
    case _46_square_fill
    case questionmark_folder_fill
    case _14_circle_fill
    case cloud_sun_fill
    case megaphone_fill
    case bookmark_fill
    case squareshape_controlhandles_on_squareshape_controlhandles
    case airplayaudio
    case die_face_6_fill
    case figure_walk_diamond_fill
    case delete_right
    case questionmark_diamond
    case sidebar_right
    case binoculars
    case scribble
    case cursorarrow_click_2
    case cloud_moon
    case figure_wave_circle
    case gobackward_60
    case phone_circle
    case t_square
    case camera_fill_badge_ellipsis
    case _30_square_fill
    case macpro_gen2_fill
    case arrow_up_to_line_alt
    case sdcard
    case cloud_bolt_rain_fill
    case rectangle_on_rectangle_angled
    case trash_circle
    case cruzeirosign_square
    case _47_circle_fill
    case square_2_stack_3d_bottom_fill
    case power
    case hryvniasign_circle
    case comb
    case plusminus
    case arrow_down_right_square
    case creditcard_fill
    case _24_circle
    case _7_square
    case tv_circle
    case _37_square_fill
    case paperplane_circle_fill
    case minus_rectangle_portrait_fill
    case camera_metering_multispot
    case key_fill
    case command_square_fill
    case turkishlirasign_square
    case arrow_down_square
    case forward_frame
    case larisign_circle
    case bubble_left_and_bubble_right
    case delete_left
    case bus
    case forward_end
    case questionmark_circle_fill
    case hand_tap
    case simcard_2_fill
    case arrow_up_left_and_down_right_magnifyingglass
    case gobackward_30_hi
    case creditcard_circle
    case doc_on_clipboard
    case arrow_left_and_right_square_fill
    case arrow_triangle_2_circlepath_doc_on_clipboard
    case bolt_badge_a
    case list_number
    case doc_plaintext
    case paperplane_circle
    case die_face_6
    case calendar
    case tv_and_hifispeaker_fill
    case bubble_right_fill
    case arrow_down_doc
    case lock_slash
    case phone_connection
    case flip_horizontal
    case xmark_bin
    case command_circle_fill
    case square_dashed
    case drop_fill
    case cloud_sun_rain
    case minus_slash_plus
    case bolt_slash_circle_fill
    case list_bullet_indent
    case cube_fill
    case _7_circle_fill
    case minus_diamond
    case arrowtriangle_left_fill_and_line_vertical_and_arrowtriangle_right_fill
    case person_crop_circle_fill_badge_checkmark
    case g_circle_fill
    case bolt_heart_fill
    case _47_square
    case guaranisign_circle
    case level
    case paperclip
    case dpad_up_fill
    case r_circle
    case mic
    case text_badge_checkmark
    case car_fill
    case _19_square_fill
    case record_circle_fill
    case battery_0
    case teletype_answer
    case newspaper_fill
    case arrow_right_arrow_left_square_fill
    case australsign_circle_fill
    case person_2_fill
    case chevron_compact_left
    case chevron_left_square
    case cursorarrow_click_badge_clock
    case waveform_path_ecg
    case envelope_arrow_triangle_branch
    case lock_rectangle_on_rectangle
    case octagon
    case greaterthan_circle
    case figure_walk_circle_fill
    case _14_circle
    case rectangle_roundedbottom_fill
    case _23_square
    case text_badge_checkmark_rtl
    case mosaic_fill
    case forward_end_alt_fill
    case doc
    case lock_rectangle_stack
    case ipod
    case signpost_right
    case envelope_circle
    case location_north_line
    case signature
    case square_slash
    case arrow_up_left_square_fill
    case eye_fill
    case calendar_badge_clock_rtl
    case questionmark_folder_fill_ar
    case exclamationmark_circle_fill
    case pano
    case book_circle_fill
    case face_smiling_fill
    case face_smiling
    case pencil_circle
    case d_square_fill
    case flowchart
    case sun_haze_fill
    case externaldrive_connected_to_line_below_fill
    case text_insert
    case airpods
    case dpad_fill
    case dot_radiowaves_right
    case xmark_circle
    case percent_ar
    case building_2_fill
    case _03_square
    case externaldrive_fill_badge_checkmark
    case gobackward_90_ar
    case video_fill
    case square_grid_3x3_bottommiddle_fill
    case lock_circle_fill
    case link
    case x_square_fill
    case arrow_turn_left_up
    case arrow_triangle_2_circlepath
    case arrow_up_left_square
    case ipodshuffle_gen3
    case _40_circle_fill
    case rectangle_lefthalf_fill
    case capslock_fill
    case seal
    case deskclock
    case crop_rotate
    case die_face_3
    case location_north_fill
    case arrow_down_left_video
    case bell_slash_fill
    case arkit
    case chevron_down_circle_fill
    case arrow_up_right_circle_fill
    case creditcard_circle_fill
    case face_dashed
    case hand_thumbsdown_fill
    case arrow_uturn_down
    case plus_rectangle_portrait_fill
    case case_fill
    case die_face_1
    case a_book_closed_he
    case textformat_superscript
    case trash
    case battery_100
    case pin_slash
    case arrow_up_doc
    case arrowshape_turn_up_right_circle
    case curlybraces_square
    case speaker_wave_3_fill
    case location_viewfinder
    case flame_fill
    case arrow_up_left_and_arrow_down_right_circle_fill
    case timer_square
    case person_crop_circle_badge_minus
    case heart
    case questionmark_square_ar
    case arrowtriangle_up_circle_fill
    case tortoise_fill
    case square_grid_3x2
    case arrow_left_circle_fill
    case sdcard_fill
    case lock_doc
    case k_square
    case eyedropper_full
    case diamond_fill
    case clock_arrow_circlepath
    case rectangle_grid_2x2_fill
    case arrow_up_left_and_arrow_down_right
    case bag_badge_plus
    case gift_circle
    case chevron_left
    case bolt_slash_fill
    case _9_square
    case t_bubble
    case _6_circle
    case arrow_left_to_line_alt
    case lasso
    case paintbrush_pointed_fill
    case speaker
    case pause_circle_fill
    case bell_fill
    case circlebadge_fill
    case macwindow
    case exclamationmark_triangle
    case circle_lefthalf_fill
    case iphone_homebutton_slash
    case wave_3_left
    case square_grid_3x3_bottomright_fill
    case arrow_counterclockwise_icloud
    case printer_dotmatrix_fill
    case number_square
    case flag_fill
    case _00_square
    case die_face_3_fill
    case ant_circle
    case sun_max
    case lightbulb_slash_fill
    case eye_slash_fill
    case mail_fill
    case italic
    case checkmark_square_fill
    case arrowshape_bounce_right_fill
    case viewfinder_circle_fill
    case mouth
    case arrowtriangle_right_circle_fill
    case captions_bubble_fill
    case mic_circle_fill
    case circle_grid_cross_right_fill
    case rectangle_stack_fill_badge_plus
    case _20_square_fill
    case a_book_closed_fill
    case car_2_fill
    case _3_square_fill
    case speaker_3
    case icloud_and_arrow_up_fill
    case _28_square_fill
    case p_square_fill
    case doc_text_magnifyingglass
    case camera
    case _43_circle_fill
    case arrow_up_bin_fill
    case externaldrive_badge_minus
    case _33_circle
    case radiowaves_left
    case arrow_down_left_video_fill_rtl
    case tv_fill
    case bolt_horizontal_fill
    case gearshape_2
    case gobackward_45_hi
    case ear_fill
    case _04_square
    case bolt_car_fill
    case divide_square_fill
    case ear_badge_checkmark
    case bolt_circle_fill
    case deskclock_fill
    case gobackward_10_ar
    case square_stack_fill
    case books_vertical_fill
    case _07_square
    case sheqelsign_square_fill
    case j_square_on_square
    case dollarsign_square
    case cursorarrow_click
    case arrow_merge
    case _40_circle
    case rectangle_grid_3x2_fill
    case bolt_fill_batteryblock
    case rectangle_fill_on_rectangle_fill_circle_fill
    case rectangle_split_2x2
    case viewfinder_circle
    case keyboard_onehanded_left
    case backward
    case lock_rectangle_on_rectangle_fill
    case line_horizontal_3_decrease_circle_fill
    case _8_circle
    case t_bubble_he
    case a_book_closed_fill_ar
    case airplayvideo
    case _34_circle
    case rectangle_grid_1x2_fill
    case arrowtriangle_down_square_fill
    case arrowtriangle_right_fill_and_line_vertical_and_arrowtriangle_left_fill
    case gearshape_fill
    case arrow_uturn_down_circle
    case kipsign_circle_fill
    case exclamationmark_square_fill
    case aspectratio_fill
    case _07_circle_fill
    case touchid
    case gauge_badge_plus
    case capsule_portrait
    case building_fill
    case curlybraces_square_fill
    case c_square
    case chevron_up_circle_fill
    case goforward_60_hi
    case _43_circle
    case externaldrive_fill_badge_icloud
    case chart_bar_doc_horizontal_fill
    case arrowshape_turn_up_left_circle
    case thermometer_sun_fill
    case equal_square
    case person_crop_circle_badge_xmark
    case arrowtriangle_right_fill
    case line_3_crossed_swirl_circle_fill
    case _37_square
    case hand_point_up_left_fill
    case star_fill
    case millsign_square
    case gobackward_15_hi
    case battery_100_bolt
    case rectangle_roundedtop
    case _19_circle
    case hourglass_badge_plus
    case person_crop_rectangle
    case squareshape_fill
    case rectangle_split_1x2_fill
    case arrowtriangle_right
    case turkishlirasign_square_fill
    case _48_square_fill
    case gear
    case questionmark_circle
    case mount
    case decrease_indent
    case _08_circle
    case at
    case translate
    case location_slash
    case exclamationmark_square
    case list_number_rtl
    case cedisign_square
    case smallcircle_circle
    case chevron_left_circle
    case car_circle_fill
    case bolt_horizontal_icloud_fill
    case e_square
    case icloud_fill
    case car_circle
    case increase_quotelevel
    case arrow_turn_up_right_iphone
    case seal_fill
    case a_square_fill
    case doc_richtext_he
    case bag_fill
    case arrow_up_and_down_righttriangle_up_righttriangle_down
    case memories_badge_plus
    case person_badge_minus_fill
    case clock
    case archivebox
    case equal_circle_fill
    case flipphone
    case square_grid_2x2_fill
    case scroll_fill
    case cursorarrow_and_square_on_square_dashed
    case k_circle_fill
    case checkmark_circle_fill
    case pencil
    case _29_square
    case circle
    case pause
    case square_and_arrow_down_fill
    case pip_remove
    case trash_slash_fill
    case rupeesign_circle_fill
    case cylinder_split_1x2_fill
    case studentdesk
    case _00_circle
    case cart_badge_plus
    case _06_square_fill
    case mail_stack
    case eye_circle
    case arrow_triangle_branch
    case rectangle_righthalf_fill
    case square_grid_3x3_bottomleft_fill
    case arrowtriangle_up_circle
    case arrow_up_circle
    case square_slash_fill
    case bus_fill
    case cursor_rays
    case macwindow_on_rectangle
    case _13_circle
    case _50_square_fill
    case arrowtriangle_left_circle
    case livephoto
    case l_joystick_down_fill
    case f_circle_fill
    case arrow_right_square
    case book_circle
    case rublesign_square
    case _9_circle_fill
    case chevron_right_square_fill
    case scribble_variable
    case r_square_on_square
    case teletype_circle
    case slider_horizontal_3
    case flag_slash
    case arrow_down
    case iphone
    case cross_circle
    case folder
    case simcard_fill
    case die_face_4_fill
    case _17_circle
    case externaldrive_badge_icloud
    case plus_magnifyingglass
    case rectangle_portrait_fill
    case checkmark_icloud
    case command
    case rectangle_righthalf_inset_fill_arrow_right
    case opticaldiscdrive_fill
    case sunrise_fill
    case applelogo
    case u_circle_fill
    case book
    case signpost_right_fill
    case _14_square
    case flip_horizontal_fill
    case rectangle_and_arrow_up_right_and_arrow_down_left
    case rectangle
    case figure_wave
    case list_bullet_below_rectangle
    case photo_on_rectangle_angled
    case phone_circle_fill
    case shield_slash_fill
    case paperplane_fill
    case cylinder_split_1x2
    case rectangle_stack_badge_person_crop
    case chevron_up
    case arrow_uturn_left_square_fill
    case arrow_right_arrow_left_square
    case lightbulb
    case wave_3_left_circle
    case cloud_snow
    case greaterthan_circle_fill
    case doc_richtext_fill
    case wind_snow
    case cloud_bolt_rain
    case q_square_fill
    case arrowtriangle_down_square
    case rectangle_bottomthird_inset_fill
    case square_grid_3x1_folder_badge_plus
    case dot_squareshape_fill
    case speaker_slash
    case location_north
    case pc
    case text_justifyleft
    case pin
    case wrench
    case hand_point_up_braille_fill
    case bed_double
    case bell_slash_circle
    case hand_point_left
    case rectangle_on_rectangle_slash
    case tengesign_square_fill
    case tengesign_circle
    case trash_fill
    case crop
    case square_grid_3x3_topmiddle_fill
    case option
    case ellipsis_circle_fill
    case coloncurrencysign_square
    case building
    case arrow_left_and_right_circle_fill
    case moon
    case rectangle_split_3x3
    case tag_slash_fill
    case hand_point_up_left
    case person_fill_xmark
    case externaldrive_connected_to_line_below
    case captions_bubble
    case plusminus_circle
    case text_bubble_fill_rtl
    case appletv
    case flag_slash_circle_fill
    case app
    case w_circle_fill
    case chevron_left_square_fill
    case _4k_tv
    case video
    case arrow_clockwise_icloud
    case doc_fill
    case `return`
    case dial_min_fill
    case arrow_left
    case australsign_square_fill
    case gobackward_90
    case cloud_drizzle
    case command_circle
    case _25_circle_fill
    case folder_badge_minus
    case w_square
    case rectangle_split_3x3_fill
    case _49_square_fill
    case plus_square_fill
    case mosaic
    case octagon_fill
    case divide_circle
    case _8_square
    case arrow_uturn_down_circle_fill
    case rectangle_split_1x2
    case rt_rectangle_roundedtop_fill
    case _13_circle_fill
    case _34_square
    case staroflife
    case indianrupeesign_square
    case gobackward_60_hi
    case video_circle
    case i_circle
    case appletv_fill
    case yensign_circle_fill
    case square_grid_3x1_fill_below_line_grid_1x2
    case folder_fill_badge_questionmark
    case arrow_triangle_turn_up_right_circle_fill
    case _12_circle_fill
    case arrow_uturn_down_square
    case tram_tunnel_fill
    case arrow_turn_up_right
    case note
    case square_3_stack_3d_top_fill
    case doc_badge_gearshape
    case dot_circle_and_cursorarrow
    case lock_square_fill
    case manatsign_circle
    case t_circle
    case ellipses_bubble
    case coloncurrencysign_circle
    case uiwindow_split_2x1
    case _1_square
    case arrow_up_and_down_circle_fill
    case ipodshuffle_gen1
    case _01_circle_fill
    case chart_bar_doc_horizontal
    case gobackward_30_ar
    case goforward_75
    case _39_square
    case music_house_fill
    case link_icloud
    case at_circle_fill
    case square_stack_3d_down_right
    case square_and_arrow_up
    case tugriksign_square
    case macwindow_on_rectangle_rtl
    case cloud_drizzle_fill
    case leaf_fill
    case externaldrive_badge_xmark
    case square_stack_3d_up
    case k_circle
    case arrow_up_right_video_fill
    case video_badge_plus
    case speaker_zzz_fill_rtl
    case pencil_tip_crop_circle_badge_minus
    case e_square_fill
    case q_circle
    case g_square
    case livephoto_play
    case _03_square_fill
    case wand_and_rays_inverse
    case u_square_fill
    case h_square
    case cursorarrow_motionlines
    case xmark_icloud_fill
    case rectangle_3_offgrid_bubble_left_fill
    case die_face_4
    case square_split_2x2
    case square_fill_and_line_vertical_and_square
    case _38_circle
    case star_square_fill
    case circles_hexagongrid
    case ticket
    case person_crop_rectangle_fill
    case australsign_square
    case mic_slash_fill
    case mappin
    case waveform_path
    case drop
    case _06_circle_fill
    case _35_circle_fill
    case pills_fill
    case _2_square_fill
    case lessthan_square_fill
    case pesetasign_circle
    case internaldrive
    case strikethrough
    case rotate_right
    case bahtsign_square_fill
    case checkmark_shield_fill
    case arrow_uturn_left_circle
    case _2_square
    case moon_zzz
    case arrowshape_turn_up_left_2_circle
    case _30_square
    case camera_on_rectangle_fill
    case video_fill_badge_plus
    case dial_fill
    case text_bubble_fill
    case _31_square_fill
    case _6_alt_circle_fill
    case bus_doubledecker
    case paperplane
    case staroflife_circle
    case _39_circle
    case archivebox_circle_fill
    case doc_richtext_fill_he
    case _5_square
    case arrow_up_arrow_down_square_fill
    case m_circle
    case radio_fill
    case bolt
    case arrow_uturn_right_square_fill
    case face_dashed_fill
    case textbox
    case xmark_rectangle_portrait_fill
    case play_rectangle_fill
    case point_fill_topleft_down_curvedto_point_fill_bottomright_up
    case mustache_fill
    case _1_magnifyingglass_ar
    case video_fill_badge_checkmark
    case arrow_down_circle
    case triangle
    case cedisign_circle_fill
    case control
    case photo_fill_on_rectangle_fill
    case tray_circle
    case chevron_right_2
    case goforward
    case circle_grid_cross_left_fill
    case j_circle_fill
    case iphone_homebutton_radiowaves_left_and_right
    case larisign_square
    case heart_circle_fill
    case r_joystick_down
    case chevron_right_square
    case iphone_homebutton
    case play
    case star_square
    case indianrupeesign_circle
    case moon_fill
    case h_square_on_square
    case folder_badge_person_crop
    case bonjour
    case tray_2_fill
    case s_square_fill
    case arrow_2_circlepath
    case n_circle
    case envelope_fill
    case goforward_90_hi
    case minus_square_fill
    case sun_min
    case die_face_5
    case battery_100_bolt_rtl
    case rectangle_inset_topleft_fill
    case pin_slash_fill
    case _01_square_fill
    case tablecells_badge_ellipsis
    case speaker_slash_rtl
    case text_redaction
    case backward_end
    case gobackward_10_hi
    case film
    case sunset_fill
    case text_book_closed
    case questionmark_folder_ar
    case homepod
    case bitcoinsign_square
    case bold_italic_underline
    case bolt_circle
    case doc_text_fill_viewfinder
    case person_crop_square_fill
    case pencil_tip_crop_circle_badge_arrow_right
    case asterisk_circle
    case camera_metering_spot
    case rotate_left
    case waveform_path_badge_plus
    case questionmark_square_fill
    case rectangle_inset_bottomright_fill
    case calendar_badge_exclamationmark
    case _11_circle
    case arrow_turn_right_up
    case guitars
    case waveform_circle_fill
    case questionmark
    case kipsign_square_fill
    case gobackward_30
    case _7_circle
    case timeline_selection
    case cart_fill_badge_plus
    case person_fill_turn_right
    case tablecells
    case macmini_fill
    case _13_square_fill
    case megaphone
    case _35_square
    case square_grid_3x3
    case _23_circle_fill
    case checkmark_seal
    case calendar_badge_minus
    case externaldrive_fill_badge_wifi
    case flashlight_on_fill
    case xmark_shield_fill
    case arrow_right
    case rectangle_fill_on_rectangle_fill_slash_fill
    case simcard
    case _39_circle_fill
    case iphone_radiowaves_left_and_right
    case dot_radiowaves_left_and_right
    case bandage_fill
    case _15_circle_fill
    case arrow_uturn_up_square
    case lt_rectangle_roundedtop
    case circle_bottomhalf_fill
    case t_circle_fill
    case larisign_square_fill
    case timer
    case _27_square_fill
    case lock_shield
    case person_crop_circle_badge_plus
    case link_circle_fill
    case heart_circle
    case safari_fill
    case mail_and_text_magnifyingglass
    case millsign_square_fill
    case _10_circle_fill
    case lasso_sparkles
    case a_square
    case shield_slash
    case c_circle
    case _13_square
    case g_circle
    case filemenu_and_cursorarrow
    case arrow_triangle_turn_up_right_diamond
    case arrow_up_right_video
    case plus_viewfinder
    case _7_square_fill
    case capsule
    case applescript_fill
    case chevron_compact_down
    case l1_rectangle_roundedbottom
    case rectangle_stack_fill
    case rectangle_dock
    case squareshape
    case tag
    case house
    case square_lefthalf_fill
    case _15_square
    case checkmark
    case guaranisign_square
    case exclamationmark_icloud
    case sheqelsign_circle_fill
    case nairasign_circle
    case waveform_path_badge_minus
    case doc_plaintext_fill
    case wrench_and_screwdriver_fill
    case sunset
    case _02_square_fill
    case alarm
    case xmark_diamond
    case waveform_path_ecg_rectangle
    case viewfinder
    case _9_alt_circle
    case message_fill
    case radio
    case leaf
    case arrow_up_right_app
    case arrow_uturn_left_circle_badge_ellipsis
    case phone_fill_connection
    case speaker_slash_circle_fill
    case s_square
    case backward_end_alt_fill
    case ipad_homebutton
    case tray_circle_fill
    case florinsign_circle_fill
    case square_on_circle
    case square_grid_3x1_folder_fill_badge_plus
    case lock_slash_fill
    case arrow_turn_up_left
    case house_fill
    case xmark_diamond_fill
    case rectangle_fill_badge_minus
    case list_number_ar
    case _2_circle
    case location_north_line_fill
    case square_split_diagonal_2x2
    case arrow_turn_up_right_iphone_fill
    case xmark
    case yensign_square_fill
    case play_circle
    case phone_fill_arrow_up_right
    case folder_circle
    case speaker_wave_2_circle_fill
    case archivebox_fill
    case pencil_tip_crop_circle
    case arrow_up_arrow_down
    case square_and_arrow_up_on_square
    case crown_fill
    case arrow_3_trianglepath
    case plus_rectangle_on_folder
    case rt_rectangle_roundedtop
    case circle_grid_2x2
    case die_face_1_fill
    case dial_max_fill
    case note_text_badge_plus
    case _23_circle
    case exclamationmark_3
    case l2_rectangle_roundedtop
    case _37_circle_fill
    case wind
    case _31_circle
    case yensign_square
    case arrowshape_turn_up_right_circle_fill
    case ellipsis_bubble_fill
    case plus_rectangle
    case arrow_down_to_line
    case arrow_right_arrow_left
    case simcard_2
    case lock_open
    case person_2_circle_fill
    case wifi_exclamationmark
    case rectangle_badge_checkmark
    case arrow_swap
    case camera_circle
    case square_fill_and_line_vertical_square_fill
    case arrow_left_and_right
    case goforward_75_ar
    case multiply
    case r1_rectangle_roundedbottom_fill
    case arrow_down_circle_fill
    case arrow_right_arrow_left_circle_fill
    case b_circle_fill
    case _09_circle_fill
    case cloud_moon_bolt
    case r2_rectangle_roundedtop_fill
    case point_topleft_down_curvedto_point_bottomright_up
    case rectangle_badge_minus
    case photo
    case plus_square
    case rectangle_portrait_arrowtriangle_2_outward
    case person_badge_plus_fill
    case _5_circle
    case rhombus_fill
    case v_square_fill
    case bold
    case forward_end_alt
    case atom
    case drop_triangle
    case escape
    case nosign
    case rectangle_fill_on_rectangle_fill
    case burst
    case chevron_down_circle
    case r_joystick_fill
    case pause_fill
    case photo_fill
    case keyboard_macwindow
    case _18_square_fill
    case percent
    case barcode
    case heart_fill
    case person_fill_and_arrow_left_and_arrow_right
    case pause_rectangle_fill
    case questionmark_video_fill_ar
    case arrow_down_right_circle
    case l_square
    case camera_metering_matrix
    case star_slash
    case arrow_down_left
    case tornado
    case _48_circle
    case goforward_60_ar
    case text_alignleft
    case wifi
    case menubar_arrow_down_rectangle
    case l1_rectangle_roundedbottom_fill
    case rectangle_inset_fill
    case r_square
    case tray_and_arrow_up
    case macpro_gen3_server
    case guaranisign_circle_fill
    case wifi_slash
    case y_square
    case arrow_up_to_line
    case eject_circle
    case _23_square_fill
    case folder_fill_badge_questionmark_ar
    case line_horizontal_star_fill_line_horizontal
    case airplane_circle_fill
    case greaterthan_square_fill
    case square_grid_3x1_below_line_grid_1x2
    case tag_circle
    case target
    case sterlingsign_circle_fill
    case bicycle
    case folder_badge_questionmark
    case rectangle_3_offgrid
    case square_righthalf_fill
    case arrow_uturn_up
    case calendar_circle_fill
    case _10_square
    case x_circle_fill
    case questionmark_circle_ar
    case i_circle_fill
    case doc_badge_gearshape_fill
    case _26_circle_fill
    case textformat_size
    case rectangle_on_rectangle
    case turkishlirasign_circle_fill
    case circle_fill
    case list_dash
    case square_split_2x2_fill
    case headphones_circle
    case circle_dashed
    case rectangle_dashed_badge_record
    case _6_circle_fill
    case dot_arrowtriangles_up_right_down_left_circle
    case memorychip
    case _09_square_fill
    case play_fill
    case rectangle_stack_badge_plus
    case puzzlepiece
    case snow
    case square_circle
    case doc_richtext_ar
    case archivebox_circle
    case table
    case goforward_30
    case externaldrive_fill_badge_person_crop
    case line_horizontal_3_circle
    case sum
    case _05_circle_fill
    case goforward_15_hi
    case arrow_triangle_2_circlepath_circle
    case sterlingsign_square_fill
    case number_circle_fill
    case mappin_and_ellipse
    case macpro_gen1
    case eurosign_square
    case h_square_fill_on_square_fill
    case arrow_triangle_capsulepath
    case clear
    case book_closed_fill
    case _03_circle
    case square_2_stack_3d
    case textformat_123
    case lessthan_circle
    case squareshape_squareshape_dashed
    case circle_grid_cross_fill
    case pencil_tip
    case _4_alt_circle_fill
    case arrow_left_and_right_righttriangle_left_righttriangle_right
    case music_note
    case pause_rectangle
    case externaldrive_fill_badge_xmark
    case rays
    case menubar_dock_rectangle_badge_record
    case _41_square
    case grid_circle_fill
    case rectangle_rightthird_inset_fill
    case a_book_closed_ar
    case clock_fill
    case rupeesign_square
    case wand_and_stars
    case circle_circle
    case loupe
    case rectangle_dashed_and_paperclip
    case arrow_down_right_and_arrow_up_left
    case _9_circle
    case rectangle_fill
    case headphones_circle_fill
    case paragraphsign
    case video_slash_fill
    case qrcode
    case display_2
    case bandage
    case bolt_horizontal
    case gauge_badge_minus
    case ticket_fill
    case sun_dust_fill
    case j_square
    case f_square_fill
    case hifispeaker
    case gobackward_75_hi
    case printer_dotmatrix_fill_and_paper_fill
    case divide
    case envelope_circle_fill
    case plus_app
    case square_split_2x1
    case circle_grid_3x3_fill
    case person_crop_circle_fill_badge_questionmark
    case note_text
    case arrow_up_left_circle_fill
    case circles_hexagonpath
    case square_and_pencil
    case burst_fill
    case pip_exit
    case _18_circle_fill
    case cloud_rain
    case pesosign_circle
    case arrow_up_right_and_arrow_down_left_rectangle
    case paintpalette_fill
    case staroflife_fill
    case arrow_up_right
    case link_circle
    case text_badge_xmark
    case trash_slash
    case rotate_3d
    case map
    case questionmark_video_fill_rtl
    case square_and_line_vertical_and_square_fill
    case arrow_triangle_pull
    case rectangle_dashed
    case _16_square
    case _50_circle
    case app_badge_fill
    case wave_3_right_circle
    case sun_dust
    case arrowtriangle_up
    case z_square_fill
    case greaterthan
    case text_book_closed_fill
    case arrow_clockwise_icloud_fill
    case arrow_uturn_right_circle_fill
    case ellipses_bubble_fill
    case music_mic
    case person_fill
    case rectangle_roundedbottom
    case _04_circle_fill
    case doc_text
    case _41_circle_fill
    case ear
    case person_2_square_stack
    case xmark_square
    case command_square
    case arrowtriangle_left_square_fill
    case mappin_circle_fill
    case eject_fill
    case mic_fill
    case staroflife_circle_fill
    case metronome_fill
    case cross
    case arrow_uturn_down_square_fill
    case a_circle_fill
    case f_circle
    case phone
    case doc_fill_badge_plus
    case applewatch_radiowaves_left_and_right
    case sunrise
    case speaker_2
    case heart_text_square
    case _8_circle_fill
    case ant
    case camera_metering_unknown_ar
    case rectangle_stack_person_crop
    case list_bullet
    case app_fill
    case apps_iphone_badge_plus
    case speaker_wave_2_fill
    case ipodshuffle_gen4
    case folder_badge_questionmark_ar
    case arrow_right_square_fill
    case gift_circle_fill
    case dock_rectangle
    case _43_square_fill
    case square_split_diagonal
    case lirasign_circle
    case _5_circle_fill
    case heart_slash_fill
    case person_crop_circle_fill
    case camera_rotate_fill
    case at_circle
    case smiley
    case arrow_down_right_circle_fill
    case _45_square
    case chevron_left_circle_fill
    case n_square
    case icloud_slash
    case hand_raised_slash
    case lock_rectangle_stack_fill
    case turkishlirasign_circle
    case wonsign_circle_fill
    case rectangle_arrowtriangle_2_outward
    case hand_draw_fill
    case menubar_dock_rectangle
    case square_split_bottomrightquarter
    case smallcircle_fill_circle_fill
    case cloud_rain_fill
    case creditcard
    case chart_bar
    case nairasign_circle_fill
    case _08_square
    case wave_3_right_circle_fill
    case rectangle_lefthalf_inset_fill
    case cursorarrow_rays
    case goforward_15
    case lessthan_circle_fill
    case _50_square
    case doc_text_fill
    case lock_icloud_fill
    case florinsign_circle
    case moon_zzz_fill
    case rectangle_fill_badge_xmark
    case phone_down_circle
    case _05_square_fill
    case i_square_fill
    case l_rectangle_roundedbottom_fill
    case francsign_circle
    case dollarsign_circle
    case slowmo
    case doc_append_fill
    case l_circle
    case rectangle_stack_fill_badge_person_crop
    case square_grid_2x2
    case externaldrive_badge_person_crop
    case tuningfork
    case cross_fill
    case arrow_up_right_circle
    case i_square
    case tengesign_square
    case rectangle_stack_fill_badge_minus
    case dot_square
    case n_square_fill
    case arrow_up_doc_fill
    case cloud_sun_bolt
    case _30_circle
    case _1_circle
    case circlebadge
    case hurricane
    case hourglass
    case _49_circle
    case t_bubble_fill_he
    case _0_circle
    case ipad_landscape
    case arrow_up_message_fill
    case _28_circle_fill
    case square_tophalf_fill
    case _28_circle
    case _17_circle_fill
    case _04_square_fill
    case backward_fill
    case bell_circle_fill
    case _6_alt_circle
    case _02_circle_fill
    case desktopcomputer
    case r_rectangle_roundedbottom_fill
    case server_rack
    case heart_slash_circle
    case switch_2
    case person_fill_checkmark
    case briefcase
    case paperclip_badge_ellipsis
    case square_3_stack_3d_middle_fill
    case network
    case _40_square_fill
    case _6_alt_square_fill
    case circle_grid_hex
    case folder_badge_gear
    case quote_bubble_fill
    case forward_end_fill
    case person_fill_badge_plus
    case gobackward
    case cloud
    case cart_badge_minus
    case square_split_diagonal_2x2_fill
    case _9_square_fill
    case arrow_up_and_person_rectangle_portrait
    case _29_square_fill
    case _5_square_fill
    case _05_square
    case gobackward_15_ar
    case projective
    case xmark_rectangle_fill
    case figure_walk_circle
    case printer_fill_and_paper_fill
    case arrow_counterclockwise_icloud_fill
    case bin_xmark
    case cloud_bolt_fill
    case swift
    case _25_square
    case plus_rectangle_fill_on_rectangle_fill
    case cross_case_fill
    case folder_badge_plus
    case square_grid_3x3_fill_square
    case arrow_triangle_turn_up_right_diamond_fill
    case x_square
    case cruzeirosign_circle
    case stop_circle
    case speaker_slash_fill
    case shield_lefthalf_fill
    case record_circle
    case square_bottomhalf_fill
    case circles_hexagongrid_fill
    case xmark_octagon
    case multiply_circle_fill
    case music_note_house
    case _3_circle
    case arrowshape_turn_up_left_2
    case hand_tap_fill
    case faceid
    case moon_stars
    case arrow_uturn_left
    case bubble_left
    case arrowtriangle_down_circle_fill
    case arrow_down_doc_fill
    case eurosign_circle_fill
    case _4_square_fill
    case forward_fill
    case calendar_circle
    case _32_square_fill
    case _09_square
    case speaker_fill
    case badge_plus_radiowaves_right
    case text_magnifyingglass
    case zr_rectangle_roundedtop
    case _41_circle
    case doc_badge_plus
    case _11_circle_fill
    case nairasign_square
    case list_star
    case _3_square
    case rb_rectangle_roundedbottom_fill
    case bookmark
    case hand_point_down_fill
    case phone_fill_arrow_right
    case rectangle_fill_on_rectangle_fill_circle
    case australsign_circle
    case lightbulb_fill
    case eyedropper_halffull
    case y_circle
    case ellipsis_rectangle
    case lock_icloud
    case externaldrive
    case _4_alt_square
    case flag_circle_fill
    case light_max
    case latch_2_case
    case eyes_inverse
    case map_fill
    case hand_wave
    case memories
    case airport_extreme
    case q_circle_fill
    case divide_square
    case camera_filters
    case thermometer_sun
    case apps_iphone_landscape_rtl
    case helm
    case cloud_heavyrain
    case arrow_uturn_up_circle
    case airport_express
    case table_fill
    case person_crop_circle_fill_badge_exclamationmark
    case _46_square
    case hryvniasign_square_fill
    case square_stack_3d_up_slash_fill
    case music_quarternote_3
    case highlighter
    case _4_circle_fill
    case dollarsign_circle_fill
    case cloud_bolt
    case eurosign_square_fill
    case magnifyingglass_circle_fill
    case icloud_and_arrow_down_fill
    case calendar_badge_clock
    case scalemass
    case tray_fill
    case bitcoinsign_circle
    case gobackward_45_ar
    case rectangle_grid_3x2
    case externaldrive_badge_plus
    case tablecells_badge_ellipsis_fill
    case cross_circle_fill
    case arrow_down_left_circle_fill
    case cloud_heavyrain_fill
    case textbox_ar
    case exclamationmark_circle
    case r_joystick
    case camera_badge_ellipsis
    case circle_grid_3x3
    case indianrupeesign_circle_fill
    case plus_bubble
    case personalhotspot
    case bold_underline
    case tugriksign_circle_fill
    case level_fill
    case b_square
    case square_and_line_vertical_and_square
    case arrow_up_and_down_square_fill
    case qrcode_viewfinder
    case shippingbox_fill
    case goforward_30_hi
    case folder_fill_badge_plus
    case eject_circle_fill
    case pencil_tip_crop_circle_badge_plus
    case view_3d
    case key_icloud_fill
    case wand_and_stars_inverse
    case scanner
    case plus_diamond
    case rectangle_compress_vertical
    case waveform_path_ecg_rectangle_fill
    case homepod_fill
    case squareshape_split_2x2
    case slash_circle
    case waveform_circle
    case flag_badge_ellipsis_fill
    case tram
    case building_columns
    case gobackward_minus
    case camera_circle_fill
    case _34_square_fill
    case rectangle_center_inset_fill
    case speaker_3_fill
    case chevron_up_square
    case w_circle
    case square_split_2x1_fill
    case person_crop_square
    case pencil_slash
    case t_bubble_fill
    case centsign_circle_fill
    case _39_square_fill
    case _28_square
    case list_triangle
    case _32_circle_fill
    case _50_circle_fill
    case rectangle_and_pencil_and_ellipsis_rtl
    case _12_square
    case arrow_triangle_merge
    case chevron_left_2
    case square_and_arrow_down_on_square_fill
    case plus_bubble_fill
    case hand_point_up
    case _19_circle_fill
    case antenna_radiowaves_left_and_right
    case arrow_up_and_down_square
    case multiply_square
    case envelope_open_fill
    case _37_circle
    case _4k_tv_fill
    case paintbrush_pointed
    case _31_circle_fill
    case info
    case suit_spade_fill
    case keyboard_badge_ellipsis
    case lungs
    case arrow_uturn_right
    case arrow_up_arrow_down_square
    case xmark_octagon_fill
    case nose_fill
    case arrow_up_and_down_righttriangle_up_fill_righttriangle_down_fill
    case eject
    case bolt_horizontal_circle
    case arrow_2_circlepath_circle_fill
    case circle_tophalf_fill
    case battery_25
    case _9_alt_square
    case wand_and_rays
    case suit_diamond
    case line_diagonal_arrow
    case _27_square
    case kipsign_circle
    case checkmark_circle
    case rectangle_portrait_arrowtriangle_2_inward
    case ipad_homebutton_landscape
    case arrow_up_square_fill
    case textformat_abc
    case metronome
    case doc_on_doc
    case questionmark_square_dashed_ar
    case sidebar_left
    case _21_square_fill
    case opticaldiscdrive
    case arrow_uturn_up_square_fill
    case phone_down
    case signature_ar
    case person_2
    case sleep
    case bolt_slash_circle
    case externaldrive_badge_checkmark
    case arrow_right_circle_fill
    case capsule_portrait_fill
    case _24_square
    case tv_circle_fill
    case sun_max_fill
    case textbox_he
    case message
    case suit_heart_fill
    case arrow_down_app
    case arrow_down_to_line_alt
    case rupeesign_square_fill
    case graduationcap
    case apps_ipad
    case hand_point_up_braille
    case placeholdertext_fill
    case _25_square_fill
    case mouth_fill
    case larisign_circle_fill
    case _36_square_fill
    case arrow_turn_left_down
    case square
    case dpad_right_fill
    case _48_circle_fill
    case delete_right_fill
    case _21_square
    case b_square_fill
    case bag_fill_badge_minus
    case pesetasign_square
    case squareshape_dashed_squareshape
    case backward_end_alt
    case forward_frame_fill
    case f_cursive_circle_fill
    case slider_horizontal_below_rectangle
    case _07_square_fill
    case hand_thumbsup_fill
    case tortoise
    case gyroscope
    case speaker_zzz_rtl
    case newspaper
    case display_trianglebadge_exclamationmark
    case y_circle_fill
    case memories_badge_minus
    case pesosign_square
    case chevron_up_square_fill
    case person_2_circle
    case car
    case restart
    case lock_open_fill
    case bubble_left_fill
    case square_and_arrow_down
    case chevron_down
    case lungs_fill
    case tv_music_note_fill
    case circle_grid_cross_up_fill
    case repeat_1
    case _9_alt_circle_fill
    case arrow_uturn_left_square
    case playpause_fill
    case r_circle_fill
    case _30_circle_fill
    case questionmark_square
    case s_circle
    case _26_square_fill
    case o_square_fill
    case v_circle_fill
    case key_icloud
    case arrow_right_arrow_left_circle
    case flashlight_off_fill
    case keyboard
    case gobackward_15
    case earpods
    case _1_square_fill
    case arrow_down_left_square
    case gamecontroller
    case chart_bar_fill
    case fn
    case bell_slash_circle_fill
    case laptopcomputer_and_iphone
    case dongsign_circle
    case _45_circle
    case _36_square
    case rectangle_and_text_magnifyingglass_rtl
    case l2_rectangle_roundedtop_fill
    case chart_bar_xaxis
    case _38_square
    case shield_fill
    case _42_square
    case ellipsis_bubble
    case o_square
    case car_2
    case _29_circle_fill
    case capsule_fill
    case livephoto_slash
    case _00_square_fill
    case cloud_hail_fill
    case line_horizontal_3_decrease_circle
    case app_gift_fill
    case mappin_slash
    case cube_box_fill
    case eyebrow
    case eye
    case _45_square_fill
    case z_circle_fill
    case stopwatch
    case h_circle
    case star
    case checkmark_seal_fill
    case building_2_crop_circle_fill
    case dot_squareshape_split_2x2
    case lessthan_square
    case arrow_up_circle_fill
    case person_fill_turn_left
    case applewatch_watchface
    case star_circle_fill
    case _44_circle_fill
    case _12_circle
    case bag_circle
    case _35_square_fill
    case arrow_counterclockwise_circle_fill
    case manatsign_square_fill
    case arrow_counterclockwise_circle
    case r_square_fill
    case grid_circle
    case message_circle_fill
    case chevron_down_square_fill
    case lock_rectangle_fill
    case _48_square
    case arrow_down_left_circle
    case _6_square
    case text_badge_minus
    case rectangle_stack
    case opticaldisc
    case arrow_uturn_left_circle_fill
    case tray_and_arrow_down
    case rotate_left_fill
    case mustache
    case l_joystick
    case plus_slash_minus
    case bag
    case e_circle_fill
    case checkmark_icloud_fill
    case arrowshape_turn_up_left_2_circle_fill
    case coloncurrencysign_square_fill
    case square_stack_3d_down_dottedline
    case scope
    case bookmark_slash_fill
    case _14_square_fill
    case flag_slash_fill
    case a_book_closed_fill_he
    case coloncurrencysign_circle_fill
    case eye_slash
    case pencil_and_outline
    case rectangle_lefthalf_inset_fill_arrow_left
    case mail_and_text_magnifyingglass_rtl
    case `case`
    case arrow_up_right_square
    case _24_circle_fill
    case text_alignright
    case bahtsign_circle_fill
    case _02_circle
    case goforward_60
    case arrowshape_bounce_right
    case magnifyingglass
    case exclamationmark_2
    case envelope_arrow_triangle_branch_fill
    case contextualmenu_and_cursorarrow
    case eye_circle_fill
    case _33_circle_fill
    case questionmark_diamond_fill
    case book_fill
    case m_square_fill
    case envelope_badge_shield_lefthalf_fill
    case wrench_and_screwdriver
    case f_cursive
    case backward_end_fill
    case rectangle_grid_1x2
    case music_note_house_fill
    case location_slash_fill
    case divide_circle_fill
    case rotate_right_fill
    case cloud_hail
    case tram_fill
    case shippingbox
    case arrow_uturn_up_circle_fill
    case doc_on_doc_fill
    case ellipsis_rectangle_fill
    case lessthan
    case rectangle_portrait
    case goforward_45_hi
    case triangle_circle_fill
    case bell_circle
    case smallcircle_fill_circle
    case teletype
    case dial_max
    case underline
    case x_circle
    case person_crop_circle_fill_badge_questionmark_ar
    case ruler_fill
    case dock_arrow_up_rectangle
    case u_circle
    case _09_circle
    case cart_fill_badge_minus
    case ear_trianglebadge_exclamationmark
    case sportscourt
    case asterisk_circle_fill
    case arrowtriangle_right_square_fill
    case at_badge_minus
    case _47_circle
    case scissors
    case greetingcard_fill
    case livephoto_badge_a
    case macmini
    case minus_rectangle_fill
    case _11_square_fill
    case goforward_15_ar
    case _1_magnifyingglass
    case indianrupeesign_square_fill
    case timelapse
    case _47_square_fill
    case cloud_moon_rain
    case _22_square
    case eyedropper
    case die_face_5_fill
    case k
    case shift_fill
    case apps_ipad_landscape
    case link_icloud_fill
    case person_fill_turn_down
    case cube
    case plusminus_circle_fill
    case diamond
    case scalemass_fill
    case _42_circle_fill
    case checkmark_rectangle_fill
    case o_circle
    case rectangle_stack_person_crop_fill
    case triangle_righthalf_fill
    case exclamationmark_arrow_triangle_2_circlepath
    case r_joystick_down_fill
    case _44_square_fill
    case person_and_arrow_left_and_arrow_right
    case _08_square_fill
    case tray_full_fill
    case mic_circle
    case person
    case square_on_square
    case _40_square
    case questionmark_video_ar
    case barcode_viewfinder
    case _17_square_fill
    case purchased_circle
    case arrowtriangle_down_fill
    case goforward_45_ar
    case arrow_up_right_video_rtl
    case iphone_slash
    case plus_rectangle_portrait
    case text_cursor
    case circle_dashed_inset_fill
    case rectangle_connected_to_line_below
    case lock_rotation
    case _36_circle_fill
    case _08_circle_fill
    case video_badge_checkmark
    case mappin_circle
    case square_grid_4x3_fill
    case hand_raised_slash_fill
    case hand_raised_fill
    case _01_square
    case cross_case
    case briefcase_fill
    case text_quote
    case _8_square_fill
    case text_cursor_he
    case arrow_up_arrow_down_circle_fill
    case eyes
    case doc_zipper
    case music_note_list
    case chevron_compact_right
    case equal_circle
    case lineweight
    case stop_circle_fill
    case camera_metering_unknown
    case table_badge_more_fill
    case gauge
    case cedisign_square_fill
    case bed_double_fill
    case square_3_stack_3d_bottom_fill
    case checkmark_square
    case chevron_down_square
    case paintbrush
    case `repeat`
    case speaker_slash_circle
    case latch_2_case_fill
    case questionmark_square_fill_ar
    case s_circle_fill
    case bag_fill_badge_plus
    case tray_and_arrow_up_fill
    case books_vertical
    case location
    case text_append
    case _9_alt_square_fill
    case arrow_clockwise_circle
    case bell_slash
    case square_split_bottomrightquarter_fill
    case camera_viewfinder
    case phone_fill
    case bag_circle_fill
    case cloud_sun_bolt_fill
    case speaker_wave_1_fill
    case _42_square_fill
    case safari
    case video_circle_fill
    case arrow_up_right_diamond_fill
    case cloud_sleet_fill
    case _44_square
    case text_magnifyingglass_rtl
    case cursorarrow
    case phone_down_fill
    case location_circle
    case hand_draw
    case phone_down_circle_fill
    case person_crop_circle_fill_badge_xmark
    case headphones
    case macpro_gen2
    case l_joystick_fill
    case number
    case cube_transparent
    case envelope_fill_badge_shield_righthalf_fill
    case paperclip_circle_fill
    
    public var name: String {
        let formattedName = rawValue.replacingOccurrences(of: "_", with: ".")
        if formattedName.first == "_" {
            return formattedName
                .dropFirst()
                .map { "\($0)" }
                .reduce("", +)
        }
        if formattedName.first == "." {
            return formattedName
                .dropFirst()
                .map { "\($0)" }
                .reduce("", +)
        }
        
        return formattedName
    }
}



UIImage(systemName: SFSym._4k_tv.name)
